spring: 
  application:
    name: Gubee backend test
  jackson:
    deserialization:
      accept-single-value-as-array: true
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    mapper:
      propagate-transient-marker: true
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true
    schemas:
    - interview_service
    locations:
    - classpath:db/schema/migration

## Server properties
server: 
  compression:
    enabled: true
    mime-types:
    - application/json
  http2:
    enabled: true
  servlet:
    context-path: /gubee_backend_test

#JDBC
jdbc:
  url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
  username: ${SPRING_DATASOURCE_USERNAME:gubee}
  password: ${SPRING_DATASOURCE_PASSWORD:gubee}
  schema: interview_service